In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('customer_shopping_behavior.csv')

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.shape

(3900, 18)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [7]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
df.isna().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
# Preenche valores nulos de 'Review Rating' com a mediana da própria categoria,
# preservando o contexto do grupo e evitando distorções causadas por valores extremos
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [10]:
df.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [12]:
# Converte nome das colunas para minuscula
df.columns = df.columns.str.lower()

In [13]:
# Substitui os espaços por underline
df.columns=df.columns.str.replace(' ','_')

In [14]:
df.head(1)

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly

In [15]:
# Dicionário de tradução das colunas
colunas_pt = {
    'customer_id': 'id_cliente',
    'age': 'idade',
    'gender': 'genero',
    'item_purchased': 'item_comprado',
    'category': 'categoria',
    'purchase_amount_(usd)': 'valor_compra_usd',
    'location': 'localizacao',
    'size': 'tamanho',
    'color': 'cor',
    'season': 'estacao',
    'review_rating': 'avaliacao',
    'subscription_status': 'status_assinatura',
    'shipping_type': 'tipo_envio',
    'discount_applied': 'desconto_aplicado',
    'promo_code_used': 'codigo_promocional_usado',
    'previous_purchases': 'compras_anteriores',
    'payment_method': 'metodo_pagamento',
    'frequency_of_purchases': 'frequencia_compras'
}

In [16]:
# Renomear colunas
df.rename(columns=colunas_pt,inplace=True)

In [17]:
df.head()

,id_cliente,idade,genero,item_comprado,categoria,valor_compra_usd,localizacao,tamanho,cor,estacao,avaliacao,status_assinatura,tipo_envio,desconto_aplicado,codigo_promocional_usado,compras_anteriores,metodo_pagamento,frequencia_compras
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [18]:
df.columns

Index(['id_cliente', 'idade', 'genero', 'item_comprado', 'categoria',
       'valor_compra_usd', 'localizacao', 'tamanho', 'cor', 'estacao',
       'avaliacao', 'status_assinatura', 'tipo_envio', 'desconto_aplicado',
       'codigo_promocional_usado', 'compras_anteriores', 'metodo_pagamento',
       'frequencia_compras'],
      dtype='object')

In [19]:
# Criar coluna de faixa etária baseada em quantis
rotulos = ['Jovem Adulto', 'Adulto', 'Meia-idade', 'Idoso']

df['faixa_etaria'] = pd.qcut(
    df['idade'],
    q=4,
    labels=rotulos
)

In [20]:
df[['idade','faixa_etaria']].head(10)

   idade  faixa_etaria
0     55    Meia-idade
1     19  Jovem Adulto
2     50    Meia-idade
3     21  Jovem Adulto
4     45    Meia-idade
5     46    Meia-idade
6     63         Idoso
7     27  Jovem Adulto
8     26  Jovem Adulto
9     57    Meia-idade

In [21]:
frequency_mapping = { 
    'Fortnightly': 14, 
    'Weekly': 7, 
    'Monthly': 30, 
    'Quarterly': 90,
    'Bi-Weekly': 14, 
    'Annually': 365, 
    'Every 3 Months': 90
 }
df['frequencia_compras_dias'] = df['frequencia_compras'].map(frequency_mapping)

In [22]:
df[['frequencia_compras_dias','frequencia_compras']].head(10)

   frequencia_compras_dias frequencia_compras
0                       14        Fortnightly
1                       14        Fortnightly
2                        7             Weekly
3                        7             Weekly
4                      365           Annually
5                        7             Weekly
6                       90          Quarterly
7                        7             Weekly
8                      365           Annually
9                       90          Quarterly

In [23]:
df.columns

Index(['id_cliente', 'idade', 'genero', 'item_comprado', 'categoria',
       'valor_compra_usd', 'localizacao', 'tamanho', 'cor', 'estacao',
       'avaliacao', 'status_assinatura', 'tipo_envio', 'desconto_aplicado',
       'codigo_promocional_usado', 'compras_anteriores', 'metodo_pagamento',
       'frequencia_compras', 'faixa_etaria', 'frequencia_compras_dias'],
      dtype='object')

In [24]:
df[['desconto_aplicado','codigo_promocional_usado']].head(10)

  desconto_aplicado codigo_promocional_usado
0               Yes                      Yes
1               Yes                      Yes
2               Yes                      Yes
3               Yes                      Yes
4               Yes                      Yes
5               Yes                      Yes
6               Yes                      Yes
7               Yes                      Yes
8               Yes                      Yes
9               Yes                      Yes

In [25]:
# compara os valores das colunas se retornar true entao ambas as colunas nao se deferenciam se
(df['desconto_aplicado'] == df['codigo_promocional_usado']).all()

np.True_

In [26]:
# Remove a coluna Redudante 
df=df.drop('codigo_promocional_usado', axis=1)

In [27]:
df.columns

Index(['id_cliente', 'idade', 'genero', 'item_comprado', 'categoria',
       'valor_compra_usd', 'localizacao', 'tamanho', 'cor', 'estacao',
       'avaliacao', 'status_assinatura', 'tipo_envio', 'desconto_aplicado',
       'compras_anteriores', 'metodo_pagamento', 'frequencia_compras',
       'faixa_etaria', 'frequencia_compras_dias'],
      dtype='object')

In [28]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (2.0.45)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
from sqlalchemy import create_engine

In [30]:
# Step 1: Definir os dados de conexão 
username = "postgres"                                # usuário padrão 
password = "SUA_SENHA_AQUI"                          # coloque a senha que você definiu na instalação 
host = "localhost"                                   # se o banco está rodando localmente 
port = "5432"                                        # porta padrão do PostgreSQL 
database = "customer_behavior"                       # nome do banco que você criou no pgAdmin

In [31]:
# Step 2: Criar a conexão
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

In [32]:
from sqlalchemy import create_engine

# Configurações atualizadas
username = "postgres"
password = "12345"  # Senha corrigida
host = "localhost"
port = "5432"
database = "customer_behavior"

# Passo 1: Criar a conexão
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Passo 2: Carregar o seu DataFrame para o banco
# Certifique-se de que a variável 'df' existe (ex: df = pd.read_csv('seu_arquivo.csv'))
try:
    table_name = "customer"
    df.to_sql(table_name, engine, if_exists="replace", index=False)
    print(f"✅ Sucesso! Dados carregados na tabela '{table_name}' do banco '{database}'.")
except NameError:
    print("❌ Erro: O DataFrame 'df' não foi definido. Você precisa carregar seus dados primeiro!")
except Exception as e:
    print(f"❌ Ocorreu um erro inesperado: {e}")

✅ Sucesso! Dados carregados na tabela 'customer' do banco 'customer_behavior'.

In [33]:
df.to_csv('c:/proj2/dados_consumidor_limpo.csv',index=False)

In [34]:
df.head(2)

,id_cliente,idade,genero,item_comprado,categoria,valor_compra_usd,localizacao,tamanho,cor,estacao,avaliacao,status_assinatura,tipo_envio,desconto_aplicado,compras_anteriores,metodo_pagamento,frequencia_compras,faixa_etaria,frequencia_compras_dias
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Meia-idade,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Jovem Adulto,14

In [35]:
# Total de cliente
Total_cliente =df['id_cliente'].count()
print(f'O total de cliente é {Total_cliente}')

O total de cliente é 3900

In [36]:
# valor medio
valor_médio =df['valor_compra_usd'].mean()
print(f'O valor médio é {valor_médio:.2f}')

O valor médio é 59.76